# Generated by Django 5.0.1 on 2024-01-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='futsal',
            name='About',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='futsal',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='futsal',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
