# Generated by Django 5.0.1 on 2024-01-22 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_futsal_about_alter_futsal_location_alter_futsal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutsalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Available', models.CharField(max_length=10)),
                ('profile_picture', models.FileField(blank=True, null=True, upload_to='profile_pictures')),
                ('futsal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.futsal')),
            ],
        ),
    ]
